version: '3.8'

services:
  localstack:
    image: localstack/localstack-full:latest
    ports:
      - 4566:4566 # LocalStack ServicePort
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack:/tmp/localstack
    environment:
      SERVICES: s3
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: ap-northeast-1
      DATA_DIR: /tmp/localstack/data
      DOCKER_HOST: unix:///var/run/docker.sock
      DISABLE_CORS_CHECKS: 1
